num_folds: 5
sample_size: 96
sample_slices: 96
encoder: resnet
decoder: cnn
per_device_train_batch_size: 2
per_device_eval_batch_size: 1
learning_rate: 1e-4
num_train_epochs: 500
num_seg_heads: 3
num_crop_samples: 4
spacing: [1.5, 1.5, 2]
model_depth: 34
resnet_shortcut: B
resnet_conv1_size: 7
resnet_conv1_stride: 1
base_feature_size: 64
resnet_layer1_stride: 2
norm_intensity: true
squared_dice: true
