num_folds: 5
sample_size: 192
sample_slices: 32
encoder: swt
base_feature_size: 36
vit_patch_size: 2
decoder: cnn
per_device_train_batch_size: 2
per_device_eval_batch_size: 1
learning_rate: 1e-2
num_train_epochs: 500
num_seg_heads: 3
num_crop_samples: 2
spacing: [1.2, 1.2, 5]
