num_folds: 5
sample_size: 128
sample_slices: 64
encoder: swt
base_feature_size: 48
vit_patch_size: 2
decoder: sunetr
per_device_train_batch_size: 2
per_device_eval_batch_size: 1
num_crop_samples: 4
learning_rate: 2e-4
weight_decay: 1e-5
num_train_epochs: 5000
num_seg_heads: 3
spacing: [1.5, 1.5, 3]
pretrain_path: pretrained/Swin-UNETR/model_swinvit.pt
norm_intensity: true
a_min: -5
a_max: 5
squared_dice: true
