channels:
  - conda-forge
dependencies:
  - python>=3.11
  - cytoolz
  - numpy
  - einops
  - pytorch
  - torchvision
  - timm
  - lightning
  - wandb
  - pandas
  - matplotlib
  - simpleitk
  - jsonargparse

  - pip
  - pip:
    - jsonargparse[signatures,omegaconf]