channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - omegaconf
  - numpy
  - einops
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::pytorch-cuda=11.8
  - pytorch-lightning
  - torchmetrics
  - timm
  - wandb
  - scikit-learn
  - pandas
  - openpyxl
  - matplotlib
  - nibabel
  - simpleitk

  - pip
  - pip:
    - evalutils
    - mmcv-full
    - mmsegmentation
    - cytoolz
    - -e third-party/MONAI
