[workspace]
name = "LuoLib"
# version is set in the [package] section
description = "Personal Python library specifically for Medical Image Analysis research"
channels = ["conda-forge"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[system-requirements]
cuda = "12"

[package]
name = "luolib"
version = "0.1.0"

[package.build] 
backend = { name = "pixi-build-python", version = "*"}
channels = [
    "conda-forge",
    "https://prefix.dev/pixi-build-backends",
]

[package.host-dependencies]
# https://pixi.sh/v0.42.1/build/dependency_types/#python-code
hatchling = "*"

[package.run-dependencies]
pytorch = "2.*"
torchvision = "*"
timm = "*"
lightning = "*"
wandb = "*"
einops = "*"
xformers = "*"
transformers = "*"

cytoolz = "*"
numpy = "*"
pandas = "*"
matplotlib = "*"

monai = "*"
simpleitk = "*"

# expand PyPI's jsonargparse[omegaconf]
jsonargparse = "*"
omegaconf = "*"

[dependencies]
# standalone usage
luolib = {path = "."}

# [pypi-dependencies]
# jsonargparse = {extras = ["omegaconf"]}
