per_device_train_batch_size: 8
learning_rate: 1e-4
num_train_epochs: 25
model_name: resnet
model_depth: 34
sample_size: 144
sample_slices: 160
pretrain_path: pretrained/med3d/pretrain/resnet_34_23dataset.pth
resnet_shortcut: A
