per_device_train_batch_size: 8
learning_rate: 1e-3
num_train_epochs: 35
model_name: resnet
model_depth: 34
sample_size: 160
sample_slices: 160
num_folds: 10
resnet_shortcut: B
resnet_conv1_size: 5
resnet_conv1_stride: 2
