_base:
  - patch192x192x48.yaml
  - ../_base/exp/seg/unet.yaml
  - scheduler: ../_base/scheduler/poly.yaml
norm_intensity: true
backbone:
  kwargs:
    kernel_sizes:
      - [3, 3, 1]
      - 3
      - 3
      - 3
      - 3
      - 3
    strides:
      - 1
      - [2, 2, 1]
      - 2
      - 2
      - 2
      - [2, 2, 1]
optim:
  name: Nesterov
  lr: 1e-2
  weight_decay: 3e-5
  kwargs:
    momentum: 0.99
