num_folds: 5
sample_size: 128
sample_slices: 32
encoder: swt
base_feature_size: 24
vit_patch_size: 2
decoder: unetr
per_device_train_batch_size: 2
per_device_eval_batch_size: 1
learning_rate: 2e-3
num_train_epochs: 300
