num_folds: 5
sample_size: 96
sample_slices: 96
encoder: swt
base_feature_size: 48
vit_patch_size: 2
decoder: sunetr
per_device_train_batch_size: 2
per_device_eval_batch_size: 1
num_crop_samples: 5
learning_rate: 1e-4
num_train_epochs: 5000
num_seg_heads: 3
spacing: [1.5, 1.5, 2]
pretrain_path: pretrained/Swin-UNETR/btcv/swin_unetr.base_5000ep_f48_lr2e-4_pretrained.pt
