num_folds: 5
sample_size: 96
sample_slices: 96
encoder: swt
base_feature_size: 48
vit_patch_size: 2
decoder: sunetr
per_device_train_batch_size: 2
per_device_eval_batch_size: 1
num_crop_samples: 4
learning_rate: 1e-4
weight_decay: 1e-5
num_train_epochs: 5000
num_seg_heads: 1
spacing: [1.5, 1.5, 2]
task_id: 1
norm_intensity: false
a_min: -175
a_max: 250
optimizer_set_to_none: true
crop: pn
squared_dice: false
dice_include_background: true
dice_nr: 1e-5
dice_dr: 1e-5
