num_folds: 5
sample_size: 256
sample_slices: 128
base_feature_size: 48
vit_patch_shape: [4, 4, 2]
mask_block_shape: [16, 16, 8]
swin_window_size: [8, 8, 4]
vit_depths: [2, 2, 6, 2]
per_device_train_batch_size: 2
per_device_eval_batch_size: 1
num_crop_samples: 4
learning_rate: 1e-4
weight_decay: 1e-5
num_train_epochs: 100
spacing: [1.5, 1.5, 3]
task_id: 1
norm_intensity: false
norm_pix_loss: false
a_min: -175
a_max: 250
scale_p: 0
shift_p: 0
optimizer_set_to_none: true
